### ISSUE TITLE
Submission not approved.

### ISSUE THREAD

**Issue by uldahlalex** [DaniRonda/boxCompany#1]
Daniel Ronda:
- Your workflows fails; the runner doesn't even locate your tests folder (misspelt, T has to be capitalised for the runner since your directory is called "Tests")
- Couldn't you at least have removed my Helper method exception signatures? It feels like you didn't even read the code you copied:
$@"
🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨
Your connection string is found, but could not be used. Are you sure you correctly inserted
the connection-string to Postgres?

Best regards, Alex
(Below is the inner exception)
🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨"

- You don't have a .gitignore file and have pushed bin and obj
- It's all right that you follow my guidelines, but it's hard to even find anything you made independently of my snippets. You even left snippets in there that are completely unused - I don't see any usages of the "ValueIsOneOf" validator for instance. 
Summary:
Everything is basically just copied and very slightly modified. This is not enough to reach submission approval. You will have to resubmit with actual business logic that you yourself write.

**Comment by DaniRonda** [comment]
Will do, is there a new deadline?

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
From: Alex Uldahl Pedersen ***@***.***>
Sent: Friday, October 27, 2023 11:28:29 AM
To: DaniRonda/boxCompany ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DaniRonda/boxCompany] Submission not approved. (Issue #1)


Daniel Ronda:

  *   Your workflows fails; the runner doesn't even locate your tests folder (misspelt, T has to be capitalised for the runner since your directory is called "Tests")
  *   Couldn't you at least have removed my Helper method exception signatures? It feels like you didn't even read the code you copied:
$@"
🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨
Your connection string is found, but could not be used. Are you sure you correctly inserted
the connection-string to Postgres?

Best regards, Alex
(Below is the inner exception)
🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨🧨"

  *   You don't have a .gitignore file and have pushed bin and obj
  *   It's all right that you follow my guidelines, but it's hard to even find anything you made independently of my snippets. You even left snippets in there that are completely unused - I don't see any usages of the "ValueIsOneOf" validator for instance.
Summary:
Everything is basically just copied and very slightly modified. This is not enough to reach submission approval. You will have to resubmit with actual business logic that you yourself write.

**Comment by uldahlalex** [comment]
It has to be approved before exam period begins in week 46.

**Comment by DaniRonda** [comment]
Hi Alex,
I wrote some more test but Im really stucked with the workflow, the code may be similar as yours as I followed your videos
